### ISSUE TITLE
Poor Integration with Extension Themes

### ISSUE THREAD

**Issue by ghost** [visualzoran/vz-file-templates#1]
First of all, just wanted to say thanks for creating such a sweet extension. I really thought something like this would face performance issues but it worked really well on my machine. 

Anyways, after testing this with an extension theme I noticed that some parts weren't affected by the color scheme. You can replicate this behavior by installing a theme and opening the tab. It would be nice if this could be resolved.

This definitely seems like it can become one of the most popular extensions on VSCode :)

**Comment by visualzoran** [comment]
Thank you for your comment. Is is a visual extension, so you are right, it should integrate with vs vode themes everywhere, where it can be done. I'll try to fix it as soon as possible.

**Comment by visualzoran** [comment]
I've just uploaded a new version of the extension to the marketplace. All elements of the UI should use current vs code theme styles.

**Comment by ghost** [comment]
New UI looks great! Closing this issue.
